language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
  - "pip install flake8"
  - "pip install ."
# command to run tests
script:
  - "flake8 ."
  - "py.test tests.py"
